maenad submission
5t3ph/stylestage pull request #76
Opened 2020-10-16 10:28 UTC by maenad

### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

2020-10-16 13:48 UTC, 5t3ph requested changes

2020-10-16 13:48 UTC, 5t3ph commented on src/_data/styles/maenad.json
> +    // Required
```suggestion
    // Required
```

2020-10-16 13:48 UTC, 5t3ph commented on src/_data/styles/maenad.json
> +    // Optional
```suggestion
    // Optional
```

2020-10-16 14:10 UTC, 5t3ph commented
Hi @maenad - a few things for you to check!

First, I wanted to make sure you were ok with the content getting this narrow before breaking to a wider width?
![image](https://user-images.githubusercontent.com/2251966/96267674-b831aa00-0f8d-11eb-934c-5d2695405fd2.png)

The color for links and buttons needs to be darker on `:hover`:
![image](https://user-images.githubusercontent.com/2251966/96267966-0f377f00-0f8e-11eb-88ae-134f60a4fca5.png)
![image](https://user-images.githubusercontent.com/2251966/96267747-cda6d400-0f8d-11eb-915c-b0d69eab5bcf.png)

Related, ideally when used as the button background, the background needs 3:1 contrast or higher with it's surroundings (or have a border that meets that condition), while keeping the button text with 4.5:1 contrast with the button background:
![image](https://user-images.githubusercontent.com/2251966/96268556-d6e47080-0f8e-11eb-84e7-c0424c15ba1e.png)
![image](https://user-images.githubusercontent.com/2251966/96268589-de0b7e80-0f8e-11eb-9ab7-56624ac4dad7.png)

I have 20/20 eyesight, but even for me this was hard to read - would you mind keeping it at a weight of `400`?
![image](https://user-images.githubusercontent.com/2251966/96268162-545bb100-0f8e-11eb-9875-f178795e823a.png)

Lastly, the `:focus` style for especially text links is not very visible especially since something is making it get cutoff a bit - can you provide a custom style? It needs to meet at least 3:1 contrast. Once you resolve the `:hover` you _could_ include `:focus` for that rule as well:
![image](https://user-images.githubusercontent.com/2251966/96268929-44909c80-0f8f-11eb-901c-7c62d77f1a24.png)

2020-10-16 14:16 UTC, maenad commented
Hello! Thanks for the quick answer.

Not sure why it is showing this way, in my file looks like this on desktop and mobile, not sure what could be wrong.

![image](https://user-images.githubusercontent.com/31748140/96269544-e1a80100-0fa0-11eb-8adb-e4a0788de1a3.png)
![image](https://user-images.githubusercontent.com/31748140/96269617-f7b5c180-0fa0-11eb-9519-d21cbc84cfa5.png)

For the rest, I am on my way to fix them, thanks for the input!

2020-10-16 14:20 UTC, 5t3ph commented
@maenad for the width I checked it by manually resizing the browser so it gets to be that narrow width on an in-between breakpoint if that helps!

2020-10-16 14:45 UTC, maenad commented
I fixed them on my main repo and the changes should appear on the same link now. Please check and let me know if it got fixed.

Thanks a lot for the prompt response, have a great weekend!

2020-10-16 16:25 UTC, maenad commented
> 
> 
> I fixed them on my main repo and the changes should appear on the same link now. Please check and let me know if it got fixed.
> 
> Thanks a lot for the prompt response, have a great weekend!

Not sure if I have to do anything else or create a new PR, please let me know to make amends if neded.

2020-10-16 16:45 UTC, 5t3ph commented
Hi @maenad - I redeployed the preview but a few changes were missed - the button background contrast still needs adjusted (3:1 against white basically) and improving `:focus` style for in-text (like in-paragraph) links. For the `:focus`, you could update your `:hover` style to include the same styling on `:focus`. Thanks!

I also just noticed that the list styling was completely removed from the "Steps to Contribute" which removes some clarity from reading the content. It's ok to remove the bullets but perhaps at least add back in some space so it doesn't appear as one paragraph.
![image](https://user-images.githubusercontent.com/2251966/96285587-c50dc800-0fa4-11eb-9770-13846bbc7b84.png)

2020-10-16 17:32 UTC, maenad commented
Changes have been made. Just in case there is any issue with the link, this should be it -- https://raw.githubusercontent.com/maenad/stylestage-submission/master/style.css

For reference, these got fixed:

![image](https://user-images.githubusercontent.com/31748140/96289872-21301680-0fbc-11eb-9803-5513e2a911f1.png)
There you can see the Steps to Contribute look better and the hovered links have more contrast.
I used this website to corroborate the contrast between elements - https://webaim.org/resources/contrastchecker/

![image](https://user-images.githubusercontent.com/31748140/96290003-4e7cc480-0fbc-11eb-8973-c3b0e0076284.png)
Buttons hover also got fixed to avoid contrast issues and to match the home one.

2020-10-17 01:57 UTC, 5t3ph commented
@maenad thanks for sticking with this! Here's the contrast I'm still concerned about:
![image](https://user-images.githubusercontent.com/2251966/96325920-feb8f000-0ff1-11eb-9cf8-3ec2d38e70b6.png)
![image](https://user-images.githubusercontent.com/2251966/96325911-e3e67b80-0ff1-11eb-82cf-57b58b5b24b9.png)

One way to resolve is to add a border that meets the contrast instead of changing the whole button background but as a UI element these "buttons" need to have at least 3:1 contrast with their surroundings 👍

2020-10-17 09:35 UTC, maenad commented
Hello again! Sorry, my bad, I had not understood the request. I fixed it now, feel free to check it whenever you have time.
Thanks for taking the time to be so thorough with this, it's great!
-- 
Everything should look like this

![image](https://user-images.githubusercontent.com/31748140/96333875-e8875000-1042-11eb-8b58-69583aa75eef.png)

Have a wonderful weekend.

2020-10-17 15:00 UTC, 5t3ph approved these changes
@maenad good to go, great work!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

2020-10-17 15:00 UTC, merged

2020-10-19 09:43 UTC, maenad commented
Thanks a lot for the opportunity!