Rainbow
5t3ph/stylestage pull request #78
Opened 2020-10-16 18:21 UTC by nicm42

### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

2020-10-16 19:37 UTC, 5t3ph requested changes

2020-10-16 19:37 UTC, 5t3ph commented on src/_data/styles/rainbow.json
> +  // Required
```suggestion
```

2020-10-16 19:37 UTC, 5t3ph commented on src/_data/styles/rainbow.json
> +  // Optional
```suggestion
```

2020-10-17 01:53 UTC, 5t3ph commented
Hi @nicm42 - one small thing!

The `:hover/:focus` on the links in the header needs to either be juuuust a little bit darker green, or bump the font-size over 18.5px:
![image](https://user-images.githubusercontent.com/2251966/96325871-6de21480-0ff1-11eb-834f-77a06eaf1b3e.png)

2020-10-17 09:54 UTC, nicm42 commented
Hi. I've fixed that text to be at least 20px.

2020-10-17 15:05 UTC, 5t3ph commented
Hi @nicm42 - looks like you need to merge your change into your master branch to wrap up this change, or update the URL here to point to your `v2` branch file.

2020-10-17 16:06 UTC, nicm42 commented
Sorry, I was convinced when I looked at it earlier that I'd done it from the branch. I've updated the master branch now.

2020-10-17 19:52 UTC, 5t3ph approved these changes
@nicm42 change is good, publishing!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

2020-10-17 19:52 UTC, merged